name: .NET Core

on: [pull_request_target]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8'     

    - name: Restore
      run: dotnet restore 
    
    - name: Build with dotnet
      run: dotnet build --no-restore
    
    - name: Run Test Suite
      run: dotnet test --no-build

    
